In [23]:
import numpy as np

In [3]:
#linspace
#sort

In [3]:
#concatenate

In [6]:
arr= np.array([[1,2,3],[4,5,6]])

In [11]:
arr.shape

(2, 3)

In [12]:
np.arange(4)

array([0, 1, 2, 3])

In [13]:
np.empty(4)

array([0.00000000e+000, 7.57577201e-312, 7.57577201e-312, 7.57577201e-312])

In [27]:
# np.linspace(arr)

In [15]:
#task 1
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
arr=np.arange(5)
print(arr)
print(arr+5)
print(arr*3)

[0 1 2 3 4]
[5 6 7 8 9]
[ 0  3  6  9 12]


In [20]:
a=np.arange(1,5)
b=np.arange(5,10)
np.cumsum(a), np.cumprod(a)

(array([ 1,  3,  6, 10]), array([ 1,  2,  6, 24]))

In [21]:
a,np.argmax(a), np.argmin(a), np.argsort([3,2,1])

(array([1, 2, 3, 4]), np.int64(3), np.int64(0), array([2, 1, 0]))

In [33]:
print(arr)

[0 1 2 3 4]
